### PR TITLE
#163522847 Make all links work

### PR DESCRIPTION
**Pull request by chuxmykel**
#### What does this PR do?
- Made all links functional
- Made create/edit and delete links on admin page function.
#### Description of Task to be completed?
- Fix all links

#### How should this be manually tested?
- Clone the repo
- Open the pages on a browser
- Click on all links to see them work.

#### Any background context you want to provide?
- None

#### Screenshots (if appropriate)
- None

### CODE REVIEW

**Comment by veeqtor** [comment]
Please, follow the Pull request convention and other convention I sent earlier on the channel.

**Comment by chuxmykel** [comment]
> Please, follow the Pull request convention and other convention I sent earlier on the channel.

Ok sir. Done

**Comment by veeqtor** [comment]
Please add a placeholder image on the profile page.

**Comment by chuxmykel** [comment]
@veeqtor New commit made

**Comment by chuxmykel** [comment]
> Please add a placeholder image on the profile page.

Placeholder image has been added and The admin form has been edited

**Comment by veeqtor** [comment]
@chuxmykel , Nice work, what do you think about reducing the width of the modals, and also I noticed the close link on the modals doesn't close the modal unless I reload the page.

**Pull request merged**
